apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: traefik
  namespace: flux-system
spec:
  path: "./traefik"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kubernetes-dashboard
  namespace: flux-system
spec:
  dependsOn:
    - name: traefik
  path: "./kubernetes-dashboard"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
