apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: kube-system
spec:
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
      version: '>=10.6.1'
  values:
    service:
      type: ClusterIP
    rbac:
      enabled: false
  interval: 1m0s

