apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: kube-system
spec:
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
      version: '>=10.6.1'
  values:
    providers:
      kubernetesCRD:
        allowCrossNamespace: true
    logs:
      general:
        level: DEBUG
      access:
        enabled: true
    ports:
      traefik:
        expose: true
      web:
        port: 80
        nodePort: 30080
        redirectTo: websecure
      websecure:
        port: 443
        nodePort: 30443
      metrics:
        port: 9101
        exposedPort: 9101
    securityContext:
      capabilities:
        drop: [ ALL ]
        add: [ NET_BIND_SERVICE ]
      readOnlyRootFilesystem: true
      runAsGroup: 0
      runAsNonRoot: false
      runAsUser: 0
    hostNetwork: true
    service:
      type: NodePort
  interval: 1m0s

